repos:
  - repo: local
    hooks:
      - id: run-make-test
        name: Run Project Tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: Ruff lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace      # Trims unnecessary spaces at the end of lines
      - id: end-of-file-fixer        # Ensures files end with a newline character
      - id: check-yaml               # Validates syntax of your YAML files
      - id: check-toml               # Validates syntax of your TOML files
      - id: check-json               # Validates syntax of your JSON files
      - id: check-merge-conflict     # Ensures no remaining git merge conflict markers (<<<<<<<) exist
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets  # Scans staged files for likely secrets and credentials
